TRAIN:
  ENABLE: True
  DATASET: imagenet
  BATCH_SIZE: 256
  EVAL_PERIOD: 10000
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
  MIXED_PRECISION: False
DATA:
  TRAIN_JITTER_SCALES_RELATIVE: [0.5, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  NUM_FRAMES: 1
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
MVIT:
  PATCH_2D: True
  ZERO_DECAY_POS_CLS: False
  MODE: "conv"
  CLS_EMBED_ON: True
  PATCH_KERNEL: [16, 16]
  PATCH_STRIDE: [16, 16]
  PATCH_PADDING: [0, 0]
  EMBED_DIM: 1024
  NUM_HEADS: 16
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.0
  DEPTH: 24
  NORM: "layernorm"
MASK:
  ENABLE: True
  PRETRAIN_DEPTH: [23]
  HEAD_TYPE: "separate"
  PRED_HOG: True
AUG:
  ENABLE: True
  RE_PROB: 0.0
  COLOR_JITTER: None             # important, not using color aug
  AA_TYPE: ""                    # important, not using color aug
  GEN_MASK_LOADER: True
  MASK_RATIO: 0.4
MIXUP:
  ENABLE: False
SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0002
  LR_POLICY: cosine
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  WARMUP_EPOCHS: 30.0
  WARMUP_START_LR: 1e-6
  OPTIMIZING_METHOD: adamw
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  ZERO_WD_1D_PARAM: True
  CLIP_GRAD_L2NORM: 0.02
MODEL:
  ARCH: maskmvit
  MODEL_NAME: MaskMViT
  LOSS_FUNC: multi_mse
  DROPOUT_RATE: 0.0
TEST:
  ENABLE: False
  DATASET: imagenet
  BATCH_SIZE: 256
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
LOG_MODEL_INFO: False
