TASK: ssl_eval
TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 16
  EVAL_PERIOD: 10
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
  MIXED_PRECISION: False
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: torchvision
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  DECODING_SHORT_SIZE: 320
MVIT:
  DEPTH: 16 # def 12
  NUM_HEADS: 3 # default 12 16
  EMBED_DIM: 384 # def 192 768 384 1024
  NUM_HEADS: 1 # default 12 16
  EMBED_DIM: 96 # def 256 192 768 384 1024
  PATCH_KERNEL: [3, 7, 7]
  PATCH_STRIDE: [2, 4, 4]  # default:empty
  PATCH_PADDING: [1, 3, 3]
  ZERO_DECAY_POS_CLS: False
  QKV_BIAS: True
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2], [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 2, 2], [15, 1, 1, 1]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  CLS_EMBED_ON: True # default: True
  USE_ABS_POS: False # default: True
  SEP_POS_EMBED: True # default: false
  REL_POS_SPATIAL: True # default: false
  REL_POS_TEMPORAL: True # default: false
  RESIDUAL_POOLING: True
  MODE: "conv"
  DROPPATH_RATE: 0.1
  LAYER_SCALE_INIT_VALUE: 0.0
  USE_MEAN_POOLING: True
  HEAD_INIT_SCALE: 0.001
AUG:
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-mstd0.5-inc1
  INTERPOLATION: bicubic
  NUM_SAMPLE: 2
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: True
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
SOLVER:
  ZERO_WD_1D_PARAM: True
  CLIP_GRAD_L2NORM: 5.0
  LAYER_DECAY: 0.75                # !
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0006                  # !
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 20.0
  LR_POLICY: cosine
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
  COSINE_AFTER_WARMUP: True
MODEL:
  NUM_CLASSES: 400
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.0
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 1
  NUM_TEMPORAL_CLIPS: [1, 3, 4, 5, 7, 10]
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
