TASK: ssl
TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  EVAL_PERIOD: 100000
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  KILL_LOSS_EXPLOSION_FACTOR: 2.0 # default 0.0 (not enforced)
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: torchvision
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  DECODING_SHORT_SIZE: 320
  TRAIN_JITTER_SCALES_RELATIVE: [0.5, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  TRAIN_CROP_NUM_TEMPORAL: 4  # default 1
MVIT:
  ZERO_DECAY_POS_CLS: False
  SEP_POS_EMBED: True # default: False needs to be false for fixed sincos
  PATCH_KERNEL: (2, 16, 16)
  PATCH_STRIDE: (2, 16, 16)
  PATCH_PADDING: (0, 0, 0)
  EMBED_DIM: 768 # vit-B
  NUM_HEADS: 12
  MLP_RATIO: 4.0
  QKV_BIAS: True
  NORM: "layernorm"
  DEPTH: 12
  DROPPATH_RATE: 0.0
  MODE: "conv"
  CLS_EMBED_ON: True
MASK:
  ENABLE: True
  MAE_ON: True #  default False
  MAE_RND_MASK: True # default: false
  PRETRAIN_DEPTH: [11]
  HEAD_TYPE: "separate_xformer"
  DECODER_DEPTH: 4
  DECODER_EMBED_DIM: 512
AUG:
  ENABLE: True
  COLOR_JITTER: None
  AA_TYPE: ""
  RE_PROB: 0.0
  MASK_RATIO: 0.9
MIXUP:
  ENABLE: False
SOLVER:
  CLIP_GRAD_L2NORM: 0.02
  BASE_LR: 1e-4
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  MAX_EPOCH: 200
  WARMUP_EPOCHS: 60.0
  BETAS: (0.9, 0.95) # default (0.9, 0.999)
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  ZERO_WD_1D_PARAM: True # default False
  WARMUP_START_LR: 1e-6
  OPTIMIZING_METHOD: adamw
MODEL:
  ARCH: maskmvit
  MODEL_NAME: MaskMViT
  LOSS_FUNC: multi_mse
  DROPOUT_RATE: 0.0
TEST:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
LOG_MODEL_INFO: False
