TASK: ssl_eval
TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 1
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_EPOCH_RESET: True
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: torchvision
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  DECODING_SHORT_SIZE: 320
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
MVIT:
  ZERO_DECAY_POS_CLS: False
  SEP_POS_EMBED: True
  PATCH_KERNEL: (2, 16, 16)
  PATCH_STRIDE: (2, 16, 16)
  PATCH_PADDING: (0, 0, 0)
  EMBED_DIM: 768 # vit-B, change depth & layerdecay
  NUM_HEADS: 12
  MLP_RATIO: 4.0
  QKV_BIAS: True
  NORM: "layernorm"
  DEPTH: 12
  MODE: "conv"
  DROPPATH_RATE: 0.1
  LAYER_SCALE_INIT_VALUE: 0.0
  USE_MEAN_POOLING: True
  HEAD_INIT_SCALE: 0.001
AUG:
  NUM_SAMPLE: 2
  ENABLE: True
  COLOR_JITTER: None
  AA_TYPE: rand-m7-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: True
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
SOLVER:
  MAX_EPOCH: 75
  LAYER_DECAY: 0.75
  LAYER_DECAY: 0.65 # vit-B
  WARMUP_EPOCHS: 5.0
  CLIP_GRAD_L2NORM: 5.0
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 6e-4
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-5
  WARMUP_START_LR: 1e-8
  LR_POLICY: cosine
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 400
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: soft_cross_entropy # default cross_entropy
  DROPOUT_RATE: 0.3
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 3
  NUM_TEMPORAL_CLIPS: [5, 7, 10]
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
