work_path=$(dirname $0)
PYTHONPATH=$PYTHONPATH:./slowfast \
python tools/run_net.py \
  --cfg $work_path/config.yaml \
  DATA.PATH_TO_DATA_DIR ./data_list/k700 \
  DATA.PATH_PREFIX /mnt/bn/kinetics-pl-hl/kinetics-pl-hl/kinetics-700/ \
  DATA.PATH_LABEL_SEPARATOR "," \
  MODEL.NUM_CLASSES 700 \
  DATA_LOADER.NUM_WORKERS 8 \
  TRAIN.EVAL_PERIOD 5 \
  TRAIN.CHECKPOINT_PERIOD 1 \
  TRAIN.BATCH_SIZE 96 \
  NUM_GPUS 8 \
  UNIFORMER.DROP_DEPTH_RATE 0.1 \
  SOLVER.MAX_EPOCH 110 \
  SOLVER.BASE_LR 3e-4 \
  SOLVER.WARMUP_EPOCHS 10.0 \
  DATA.TEST_CROP_SIZE 224 \
  TEST.NUM_ENSEMBLE_VIEWS 1 \
  TEST.NUM_SPATIAL_CROPS 1 \
  RNG_SEED 6666 \
  OUTPUT_DIR $work_path
