PROJ_DIR="YOU_PROJECT_DIR"

export UPLOAD_SOURCE={PROJ_DIR}/slowfast_MViTv2_S_16x4_PMV/scratch_crop_224_shorter_resize_256_320_bs_32x4__200e/
export EXP_EXCUATION_SCRIPT=run_SlowFast_MViTv2_S_16x4_PMV_release.sh

chmod +x exc_slowfast.sh

./exc_slowfast.sh \
DATA_LOADER.NUM_WORKERS 10 \
DATA.DECODING_BACKEND pyav \
DATA.TRAIN_CROP_SIZE 224 \
SOLVER.MAX_EPOCH 200 \
TRAIN.BATCH_SIZE 32 \
SOLVER.BASE_LR 1e-4 \
NUM_GPUS 8 \
SOLVER.BASE_LR_SCALE_NUM_SHARDS True \
DATA.PM_SUBSET _pmv400 \
DATA.PATH_PREFIX {PROJ_DIR}/PMV_dataset/ \
MODEL.NUM_CLASSES 400 \
DATA.TRAIN_JITTER_ASPECT_RELATIVE [] \
DATA.TRAIN_JITTER_SCALES_RELATIVE []



export UPLOAD_SOURCE={PROJ_DIR}/slowfast_MViTv2_S_16x4_PMV/scratch_crop_224_default_resize_256_320_bs_32x4__200e/
export EXP_EXCUATION_SCRIPT=run_SlowFast_MViTv2_S_16x4_PMV_release.sh

chmod +x exc_slowfast.sh

./exc_slowfast.sh \
DATA_LOADER.NUM_WORKERS 10 \
DATA.DECODING_BACKEND pyav \
DATA.TRAIN_CROP_SIZE 224 \
SOLVER.MAX_EPOCH 200 \
TRAIN.BATCH_SIZE 32 \
SOLVER.BASE_LR 1e-4 \
NUM_GPUS 8 \
SOLVER.BASE_LR_SCALE_NUM_SHARDS True \
DATA.PM_SUBSET _pmv400 \
DATA.PATH_PREFIX {PROJ_DIR}/PMV_dataset/ \
MODEL.NUM_CLASSES 400


export UPLOAD_SOURCE={PROJ_DIR}/slowfast_MViTv2_S_16x4_PMV/scratch_crop_256_192_shorter_resize_256_320_bs_32x4__200e/
# export UPLOAD_SOURCE=/mnt/bn/kinetics-pl/output/slowfast_MViTv2_S_16x4_PMV_v0.3.1/test
export EXP_EXCUATION_SCRIPT=run_SlowFast_MViTv2_S_16x4_PMV_release.sh

chmod +x exc_slowfast.sh

./exc_slowfast.sh \
DATA_LOADER.NUM_WORKERS 10 \
DATA.DECODING_BACKEND pyav \
DATA.TRAIN_CROP_SIZE 224 \
SOLVER.MAX_EPOCH 200 \
TRAIN.BATCH_SIZE 32 \
SOLVER.BASE_LR 1e-4 \
NUM_GPUS 8 \
SOLVER.BASE_LR_SCALE_NUM_SHARDS True \
DATA.PM_SUBSET _pmv400 \
DATA.PATH_PREFIX {PROJ_DIR}/PMV_dataset/ \
MODEL.NUM_CLASSES 400 \
DATA.TRAIN_JITTER_ASPECT_RELATIVE [] \
DATA.TRAIN_JITTER_SCALES_RELATIVE [] \
DATA.TRAIN_JITTER_SCALES_AUTO_ADJUST True DATA.TRAIN_CROP_SIZE_RECT [256,192]



export UPLOAD_SOURCE={PROJ_DIR}/slowfast_MViTv2_S_16x4_PMV/scratch_crop_288_192_shorter_resize_256_320_bs_32x4__200e/
# export UPLOAD_SOURCE=/mnt/bn/kinetics-pl/output/slowfast_MViTv2_S_16x4_PMV_v0.3.1/test
export EXP_EXCUATION_SCRIPT=run_SlowFast_MViTv2_S_16x4_PMV_release.sh

chmod +x exc_slowfast.sh

./exc_slowfast.sh \
DATA_LOADER.NUM_WORKERS 10 \
DATA.DECODING_BACKEND pyav \
DATA.TRAIN_CROP_SIZE 224 \
SOLVER.MAX_EPOCH 200 \
TRAIN.BATCH_SIZE 32 \
SOLVER.BASE_LR 1e-4 \
NUM_GPUS 8 \
SOLVER.BASE_LR_SCALE_NUM_SHARDS True \
DATA.PM_SUBSET _pmv400 \
DATA.PATH_PREFIX {PROJ_DIR}/PMV_dataset/ \
MODEL.NUM_CLASSES 400 \
DATA.TRAIN_JITTER_ASPECT_RELATIVE [] \
DATA.TRAIN_JITTER_SCALES_RELATIVE [] \
DATA.TRAIN_JITTER_SCALES_AUTO_ADJUST True DATA.TRAIN_CROP_SIZE_RECT [288,192]
