PROJ_DIR="YOU_PROJECT_DIR"

export UPLOAD_SOURCE={PROJ_DIR}/uniformer_s16x4_PMV/scratch_crop_224_resize_256_320_96x4_shorter_lr2e-4_100e_re/
export EXP_EXCUATION_SCRIPT=run_uniformer_s16x4_PMV_release.sh
./exc_uniformer.sh \
	DATA_LOADER.NUM_WORKERS 10 \
	DATA.DECODING_BACKEND decord \
	DATA.TRAIN_CROP_SIZE 224 \
	SOLVER.MAX_EPOCH 100 \
	TRAIN.BATCH_SIZE 96 \
	SOLVER.BASE_LR 0.0002 \
	NUM_GPUS 8 \
	SOLVER.BASE_LR_SCALE_NUM_SHARDS True \
	DATA.PM_SUBSET _pmv400 \
	DATA.PATH_PREFIX {PROJ_DIR}/PMV_dataset/ \
	UNIFORMER.PRETRAIN_NAME "''" \
	SOLVER.WARMUP_EPOCHS 10.0 \
	MODEL.NUM_CLASSES 400 \
	DATA.TRAIN_JITTER_ASPECT_RELATIVE [] \
	DATA.TRAIN_JITTER_SCALES_RELATIVE []


export UPLOAD_SOURCE={PROJ_DIR}/uniformer_s16x4_PMV/scratch_crop_224_resize_256_320_96x4_default_lr2e-4_100e/
export EXP_EXCUATION_SCRIPT=run_uniformer_s16x4_PMV_release.sh

chmod +x exc_uniformer.sh

./exc_uniformer.sh \
	DATA_LOADER.NUM_WORKERS 10 \
	DATA.DECODING_BACKEND decord \
	DATA.TRAIN_CROP_SIZE 224 \
	SOLVER.MAX_EPOCH 100 \
	TRAIN.BATCH_SIZE 96 \
	SOLVER.BASE_LR 0.0002 \
	NUM_GPUS 8 \
	SOLVER.BASE_LR_SCALE_NUM_SHARDS True \
	DATA.PM_SUBSET _pmv400 \
	DATA.PATH_PREFIX {PROJ_DIR}/PMV_dataset/ \
	UNIFORMER.PRETRAIN_NAME "''" \
	SOLVER.WARMUP_EPOCHS 10.0 \
	MODEL.NUM_CLASSES 400 
    

export UPLOAD_SOURCE={PROJ_DIR}/uniformer_s16x4_PMV/scratch_crop_256_192_resize_256_320_96x4_shorter_lr2e-4_100e/
export EXP_EXCUATION_SCRIPT=run_uniformer_s16x4_PMV_release.sh
./exc_uniformer.sh \
	DATA_LOADER.NUM_WORKERS 10 \
	DATA.DECODING_BACKEND decord \
	DATA.TRAIN_CROP_SIZE 224 \
	SOLVER.MAX_EPOCH 100 \
	TRAIN.BATCH_SIZE 96 \
	SOLVER.BASE_LR 0.0002 \
	NUM_GPUS 8 \
	SOLVER.BASE_LR_SCALE_NUM_SHARDS True \
	DATA.PM_SUBSET _pmv400 \
	DATA.PATH_PREFIX {PROJ_DIR}/PMV_dataset/ \
	UNIFORMER.PRETRAIN_NAME "''" \
	SOLVER.WARMUP_EPOCHS 10.0 \
	MODEL.NUM_CLASSES 400 \
	DATA.TRAIN_JITTER_ASPECT_RELATIVE [] \
	DATA.TRAIN_JITTER_SCALES_RELATIVE [] \
    DATA.TRAIN_JITTER_SCALES_AUTO_ADJUST True DATA.TRAIN_CROP_SIZE_RECT [256,192]
    


export UPLOAD_SOURCE={PROJ_DIR}/uniformer_s16x4_PMV/scratch_crop_288_192_resize_256_320_96x4_shorter_lr2e-4_100e/
export EXP_EXCUATION_SCRIPT=run_uniformer_s16x4_PMV_release.sh
./exc_uniformer.sh \
	DATA_LOADER.NUM_WORKERS 10 \
	DATA.DECODING_BACKEND decord \
	DATA.TRAIN_CROP_SIZE 224 \
	SOLVER.MAX_EPOCH 100 \
	TRAIN.BATCH_SIZE 96 \
	SOLVER.BASE_LR 0.0002 \
	NUM_GPUS 8 \
	SOLVER.BASE_LR_SCALE_NUM_SHARDS True \
	DATA.PM_SUBSET _pmv400 \
	DATA.PATH_PREFIX {PROJ_DIR}/PMV_dataset/ \
	UNIFORMER.PRETRAIN_NAME "''" \
	SOLVER.WARMUP_EPOCHS 10.0 \
	MODEL.NUM_CLASSES 400 \
	DATA.TRAIN_JITTER_ASPECT_RELATIVE [] \
	DATA.TRAIN_JITTER_SCALES_RELATIVE [] \
    DATA.TRAIN_JITTER_SCALES_AUTO_ADJUST True DATA.TRAIN_CROP_SIZE_RECT [288,192]
    
